[server]
bind_addr = "0.0.0.0:2333"

[server.transport]
type = "tls"
[server.transport.tls]
pkcs12 = "examples/tls/identity.pfx"
pkcs12_password = "1234"

[server.users.alice]
key = "alice_secret"
port_block = "20000-20999"
tcp = ["80"]
