[client]
remote_addr = "localhost:2333"
user = "alice"
key = "alice_secret"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "xrpknQcAagcd/b9foMwxSCD+EindWxq450NEONk8XQo="
