[server]
bind_addr = "0.0.0.0:2333"

[server.transport]
type = "noise"
[server.transport.noise]
local_private_key = "QLYMByBnjgM254zT6YKaBVvuAA61swyZfFxoA/SKZHM="

[server.users.alice]
key = "alice_secret"
port_block = "20000-20999"
tcp = ["80"]
