# rathole configuration can put in one file as long as running mode is specified via cli

[client]
remote_addr = "localhost:2333"
user = "alice"
key = "alice_secret"

[server]
bind_addr = "0.0.0.0:2333"

[server.users.alice]
key = "alice_secret"
port_block = "20000-20999"
tcp = ["80"]
