[package]
name = "rathole-desktop"
version = "0.6.2"
edition = "2021"
description = "Desktop UI for the rathole client"
license = "Apache-2.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rathole = { path = "..", default-features = false, features = [
    "client",
    "native-tls",
    "noise",
    "websocket-native-tls",
    "hot-reload",
] }
